
Neos:
  Neos:
    Ui:
      resources:

        # we only load the CKEditor Inspector in Dev mode!
        javascript:
          'Sandstorm.CkEditorInspector:Inspector':
            resource: resource://Sandstorm.CkEditorInspector/Public/Inspector/Plugin.js
        stylesheets:
          'Sandstorm.CkEditorInspector:Inspector':
            resource: resource://Sandstorm.CkEditorInspector/Public/Inspector/Plugin.css
